version: '3.6'
services:
  client-frontend:
    build: ./eaii-product-client
    ports:
      - 3000:3000
    depends_on:
      - graphql-engine
  backend:
    build: ./eaii-auth
    ports:
      - 4001:4001
    env_file:
      - .env
    depends_on:
      - graphql-engine
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.24.1.cli-migrations-v3
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    env_file:
      - .env
    depends_on:
      - postgres
  admin-frontend:
    build: ./eaii-product
    ports:
      - 3001:3001
    depends_on:
      - graphql-engine
  
volumes:
  db_data: